# Generated by Django 4.1.dev20211123065844 on 2022-08-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmyweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textodetalle',
            options={'verbose_name': 'TextoDetalle', 'verbose_name_plural': 'TextoDetalles'},
        ),
    ]
