# Generated by Django 4.1 on 2022-08-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmyweb', '0002_alter_textodetalle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textodetalle',
            name='contenido',
            field=models.TimeField(),
        ),
    ]
