# Generated by Django 4.1 on 2022-08-12 13:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('appmyweb', '0003_alter_textodetalle_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textodetalle',
            name='contenido',
            field=tinymce.models.HTMLField(),
        ),
    ]
