# Generated by Django 2.1.3 on 2022-08-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmyweb', '0004_alter_textodetalle_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textodetalle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
