# Generated by Django 4.1.dev20211123065844 on 2022-07-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_servicio_options_alter_servicio_contenido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
