# Generated by Django 4.1 on 2022-08-16 19:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_servicio_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='contenido',
            field=tinymce.models.HTMLField(),
        ),
    ]
