# Generated by Django 2.1.5 on 2022-08-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='categorias',
        ),
        migrations.AddField(
            model_name='articulo',
            name='categorias',
            field=models.ManyToManyField(to='productos.Categoria'),
        ),
    ]
