# Generated by Django 4.1.dev20211123065844 on 2022-06-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_contenido_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
        migrations.AlterField(
            model_name='servicio',
            name='contenido',
            field=models.CharField(max_length=1000),
        ),
    ]
